name: Dart
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with: null
        channel: stable
      - name: Install dependencies
        run: dart pub get
      - name: Build release APK
        run: flutter build apk --release
      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: flutter-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
      - name: Run tests
        run: dart test
